In [1]:
import torch

In [24]:
x = torch.randint(low=0,high =10, size=[5,1,2,4])
class_idx = [7,8,9,0]
x

tensor([[[[1, 7, 1, 3],
          [0, 0, 3, 5]]],


        [[[5, 4, 2, 4],
          [8, 4, 9, 6]]],


        [[[8, 2, 0, 5],
          [8, 2, 9, 9]]],


        [[[4, 8, 9, 0],
          [3, 0, 0, 3]]],


        [[[4, 2, 4, 0],
          [8, 9, 2, 6]]]])

In [28]:

# Create a one-hot mask tensor for the specified class indices
class_mask = torch.zeros((10,))
class_mask[class_idx] = 1
class_mask = class_mask.view(1, 10, 1, 1)


In [30]:

# Expand the mask tensor to match the shape of the input tensor
expanded_mask = class_mask.expand([5,1,2,4])

RuntimeError: The expanded size of the tensor (1) must match the existing size (10) at non-singleton dimension 1.  Target sizes: [5, 1, 2, 4].  Tensor sizes: [1, 10, 1, 1]

In [37]:
import torch

# Assuming you have a tensor of class labels
class_labels = torch.randint(low=0,high =5, size=[5,1,2,4])

# Define the classes you want to create a mask for
target_classes = [1, 3, 5]

# Create a mask tensor with the same shape as the class_labels tensor
mask = torch.zeros_like(class_labels, dtype=torch.bool)

# Set the elements of the mask to True for the target classes
for target_class in target_classes:
    mask = mask | (class_labels == target_class)

# Print the mask
print(class_labels, mask)


tensor([[[[3, 1, 4, 0],
          [1, 1, 1, 0]]],


        [[[3, 4, 1, 1],
          [3, 0, 2, 1]]],


        [[[2, 2, 1, 2],
          [1, 4, 0, 3]]],


        [[[2, 4, 2, 4],
          [2, 2, 0, 3]]],


        [[[4, 1, 2, 3],
          [3, 1, 1, 2]]]]) tensor([[[[ True,  True, False, False],
          [ True,  True,  True, False]]],


        [[[ True, False,  True,  True],
          [ True, False, False,  True]]],


        [[[False, False,  True, False],
          [ True, False, False,  True]]],


        [[[False, False, False, False],
          [False, False, False,  True]]],


        [[[False,  True, False,  True],
          [ True,  True,  True, False]]]])


In [40]:
import torch

# Assuming you have a tensor of class labels
class_labels = torch.randint(low=0,high =10, size=[5,1,2,4])

# Define the classes you want to create a mask for
target_classes = [1, 3, 5]

# Create a mask tensor using torch.eq() and torch.any()
mask = torch.any(torch.eq(class_labels.squeeze(), torch.tensor(target_classes)), dim=1)

print(class_labels, mask)


RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 2

In [42]:
import torch

# Assuming you have a tensor of class labels
class_labels =  torch.randint(low=0,high =10, size=[5,1,2,4])

# Define the classes you want to create a mask for
target_classes = [9,8,7]

# Create a mask tensor using torch.isin()
mask = torch.isin(class_labels, torch.tensor(target_classes))

# Print the mask
print(class_labels, mask)


tensor([[[[3, 5, 8, 2],
          [1, 4, 5, 8]]],


        [[[6, 2, 0, 4],
          [3, 2, 6, 2]]],


        [[[8, 7, 0, 7],
          [0, 8, 9, 3]]],


        [[[7, 1, 9, 7],
          [0, 1, 7, 6]]],


        [[[5, 7, 3, 5],
          [6, 4, 6, 5]]]]) tensor([[[[False, False,  True, False],
          [False, False, False,  True]]],


        [[[False, False, False, False],
          [False, False, False, False]]],


        [[[ True,  True, False,  True],
          [False,  True,  True, False]]],


        [[[ True, False,  True,  True],
          [False, False,  True, False]]],


        [[[False,  True, False, False],
          [False, False, False, False]]]])
