In [1]:
import os
import sys
import numpy as np
import pandas as pd
from PIL import Image
from tqdm import tqdm_gui
import torch
sys.path.append("..") 


In [2]:
%load_ext autoreload
%autoreload 2

In [29]:
img_dir = '/home/valerie/data/rocky_tlm/rgb/'  #'/data/xiaolong/rgb'
dem_dir = '/home/valerie/data/rocky_tlm/dem/' # /data/xiaolong/dem'
mask_dir = '/home/valerie/data/ace_alps/mask'
few_index = [2,3,4,6]
ds_csv = '/home/valerie/Projects/Alps_LCC/data/split_subset/train_subset.csv'

In [35]:
from XL.data_preprocessing.data_preprocess import *

#label_selection(label_path=mask_dir, rgb_path=img_dir,threshold=0.1)

In [5]:
238317 /398921 *100

59.740399728267

In [6]:
from XL.data_preprocessing.data_preprocess import class_distribution

for path in os.listdir('data/split/'):
    
    class_distribution('data/split/'+path,path.replace('.csv','')+'_class_distribution')

In [9]:
few_categories_tile_selection('/home/valerie/Projects/Alps_LCC/data/split/test_dataset.csv',few_index=few_index)

  0%|          | 0/45907 [00:00<?, ?it/s]

100%|██████████| 45907/45907 [00:35<00:00, 1301.89it/s]


In [38]:
df = pd.read_csv('/home/valerie/Projects/Alps_LCC/data/split/train_dataset.csv')

rbg                  dem                   mask  \
0       26193_11033_rgb.tif  26193_11033_dem.tif  26193_11033_label.tif   
1       26455_11059_rgb.tif  26455_11059_dem.tif  26455_11059_label.tif   
2       25602_11133_rgb.tif  25602_11133_dem.tif  25602_11133_label.tif   
3       25750_11179_rgb.tif  25750_11179_dem.tif  25750_11179_label.tif   
4       25659_11101_rgb.tif  25659_11101_dem.tif  25659_11101_label.tif   
...                     ...                  ...                    ...   
137716  26754_11508_rgb.tif  26754_11508_dem.tif  26754_11508_label.tif   
137717  26104_11404_rgb.tif  26104_11404_dem.tif  26104_11404_label.tif   
137718  25931_11295_rgb.tif  25931_11295_dem.tif  25931_11295_label.tif   
137719  26184_11131_rgb.tif  26184_11131_dem.tif  26184_11131_label.tif   
137720  25890_10866_rgb.tif  25890_10866_dem.tif  25890_10866_label.tif   

        mainclass  
0             9.0  
1             1.0  
2            10.0  
3             1.0  
4             1.0  
...           ...  
137716       10.0  
137717        9.0  
137718       10.0  
137719       10.0  
137720        9.0  

[137721 rows x 4 columns]

In [22]:
df = pd.read_csv('/home/valerie/Projects/Alps_LCC/data/split/train_dataset.csv')
df['mainclass'].value_counts(dropna=False)

10.0    40490
1.0     39967
9.0     34448
14.0    15675
11.0     1621
7.0      1457
13.0     1115
15.0      985
12.0      809
2.0       793
3.0       304
4.0        32
5.0        25
Name: mainclass, dtype: int64

In [31]:
df = pd.read_csv('/home/valerie/Projects/Alps_LCC/data/split_subset/train_subset.csv')
df['mainclass'].value_counts(dropna=False)


10.0    4049
1.0     3997
9.0     3445
14.0    1568
11.0     162
7.0      146
13.0     112
15.0      98
12.0      81
2.0       79
3.0       30
4.0        3
5.0        2
Name: mainclass, dtype: int64

In [25]:
df = pd.read_csv('/home/valerie/Projects/Alps_LCC/data/split_subset/train_subset_few.csv')
df['few'].value_counts(dropna=False)

0    12519
1     1253
Name: few, dtype: int64

In [34]:
from XL.lib.dataset.SwissImage import SwissImage

ds = SwissImage(dataset_csv=ds_csv, img_dir= img_dir,dem_dir=dem_dir,mask_dir=mask_dir)
cal_mean_std(ds)

  0%|          | 0/13772 [00:00<?, ?it/s]

100%|██████████| 13772/13772 [00:37<00:00, 368.68it/s]


(array([-4.61502776e-05,  0.00000000e+00,  0.00000000e+00]),
 array([1.00000567, 0.        , 0.        ]))

In [37]:
compute_mean_std(ds)

  0%|          | 0/13772 [00:00<?, ?it/s]

100%|██████████| 13772/13772 [00:38<00:00, 361.18it/s]


(array([-1.84600861,  6.90439665, -6.835506  ,  0.50212398]),
 array([0.46730447, 0.48176057, 0.4038767 , 0.01979469]))